name: Python application

on:
  workflow_call: 
    inputs:
        role-to-assume:
          description: 'AWS role passed from the caller workflow'
          required: true
          type: string 


permissions:
  id-token: write
  contents: read

jobs:
  deployec2stack:
    runs-on: ubuntu-latest        
    steps:
    - uses: actions/checkout@v3
    
    - name: Configure AWS credentials for dev account
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: ${{inputs.role-to-assume}}
        aws-region: ap-southeast-2

    - name: Show AWS Caller Identity
      run: aws sts get-caller-identity

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
            python3 -m pip install --upgrade pip
            python3 -m pip install aws-cdk-lib
    - name: Set up node
      uses: actions/setup-node@v2
      with:
        node-version: "14"
    
    - name: Install cdk
      run: npm install -g aws-cdk

    - name: Get current time
      uses: josStorer/get-current-time@v2
      id: current-time
      with:
        format: YYYYMMDD-HH
    - name: Use current time
      env:
        TIME: "${{ steps.current-time.outputs.time }}"
        R_TIME: "${{ steps.current-time.outputs.readableTime }}"
        F_TIME: "${{ steps.current-time.outputs.formattedTime }}"
        YEAR: "${{ steps.current-time.outputs.year }}"
        DAY: "${{ steps.current-time.outputs.day }}"
      run: echo $TIME $R_TIME $F_TIME $YEAR $DAY
      
    - name: Move to workspace directory
      run: cd ${GITHUB_WORKSPACE} 
      
    - name: Deploy 
      run: make ec2
