# This workflow installs Go,CDK dependencies and deploy stack

name: Stack_Deploy

on:
  workflow_call: 
    inputs:
        role-to-assume:
          description: 'GitHub OIDC provider of AWS account'
          required: true
          type: string 

jobs:

  Deploy_Stack:
  
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
    - uses: actions/checkout@v3
    
    - name: Configure AWS credentials for dev account
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: ${{inputs.role-to-assume}}
        aws-region: ap-southeast-2

    - name: Show AWS Caller Identity
      run: aws sts get-caller-identity
      
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '>1.16'

    - name: Check Go Version
      run: go version

    - name: Set up node
      uses: actions/setup-node@v2
      with:
        node-version: "14"
    
    - name: Install cdk
      run: npm install -g aws-cdk
      
    - name: Move to workspace directory
      run: cd ${GITHUB_WORKSPACE} 
      
    - name: Deploy stack
      run: make deploy    
