# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  workflow_call:
    inputs:
        role-to-assume:
          description: 'AWS role passed from the caller workflow'
          required: true
          type: string 


permissions:
  id-token: write
  contents: read

jobs:

  deletEc2PRstack:
    runs-on: ubuntu-latest        
    steps:
    - uses: actions/checkout@v3
    
    - name: Configure AWS credentials for dev account
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: ${{inputs.role-to-assume}}
        aws-region: ap-southeast-2

    - name: Show AWS Caller Identity
      run: aws sts get-caller-identity

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
            python3 -m pip install --upgrade pip
            python3 -m pip install aws-cdk-lib
    - name: Set up node
      uses: actions/setup-node@v2
      with:
        node-version: "14"
    
    - name: Install cdk
      run: npm install -g aws-cdk
      
    - name: Move to workspace directory
      run: cd ${GITHUB_WORKSPACE} 
      
    - name: Delete stack 
      run: make destroy  
